version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'redis:7.0.0-bullseye'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
  